apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tangserver-pvc
  namespace: nbde
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
